import '../styles/globals.css';
import '../styles/themes.css'; // Add this line

import { TTSProvider } from '../context/TTSContext';

/**
 * Custom Next.js App component
 * 
 * This is the application wrapper component that manages application-wide state and styling.
 * It wraps the entire application with the TTSProvider to make TTS functionality
 * available throughout the application.
 * 
 * @param {Object} props - Component props
 * @param {React.Component} props.Component - The active page component
 * @param {Object} props.pageProps - Props generated by Next.js for the page
 * @returns {JSX.Element} The rendered application with context providers
 */
function MyApp({ Component, pageProps }) {
  return (
    <TTSProvider>
      <Component {...pageProps} />
    </TTSProvider>
  );
}

export default MyApp;
