import '../styles/globals.css';
import '../styles/themes.css';

import { TTSProvider } from '../context/TTSContext';
import { NotificationProvider } from '../context/notificationContext';
import { TTSSessionProvider } from '../context/TTSSessionContext';
import { ApiKeyConfirmProvider } from '../context/apiKeyConfirmContext';
import ApiKeyConfirmModal from '../components/modals/ApiKeyConfirmModal';

/**
 * Custom Next.js App component
 * 
 * This is the application wrapper component that manages application-wide state and styling.
 * It wraps the entire application with the TTSProvider to make TTS functionality
 * available throughout the application.
 * 
 * @param {Object} props - Component props
 * @param {React.Component} props.Component - The active page component
 * @param {Object} props.pageProps - Props generated by Next.js for the page
 * @returns {JSX.Element} The rendered application with context providers
 */
function MyApp({ Component, pageProps }) {
  return (
    <NotificationProvider>
      <TTSProvider>
        <TTSSessionProvider>
          <ApiKeyConfirmProvider>
            <Component {...pageProps} />
            <ApiKeyConfirmModal />
          </ApiKeyConfirmProvider>
        </TTSSessionProvider>
      </TTSProvider>
    </NotificationProvider>
  );
}

export default MyApp;
